### ISSUE TITLE
features.h dependency and OS X

### ISSUE THREAD

**Issue by jelmervdl** [bneijt/ccbuild#24]
I tried to compile ccbuild on OS X but it got stuck on features.h, which as far as I can tell Mac OS X does not have. But it seems it is only used in the wordexp implementation?

As an experiment, I removed the included wordexp implementation and just used the wordexp.h which is available on OS X by default. After removing all references to wordexp and features.h from the makefiles, ccbuild did compile and it does seem to work (I've only tried it on one project so far)

(I compiled bobcat as described by [JP van Oosten](http://www.jpvanoosten.nl/blog/2011/07/23/fbb-software-bobcat-bisoncpp-on-the-mac/) with a few changes, and used GNU gcc 4.6, not Apple's llvm-gcc to compile ccbuild.)

**Comment by bneijt** [comment]
Have not gotten it to work and never got around to trying it again. So it finally dropped of my TODO list.
