### ISSUE TITLE
ccbuild fails to build flex 2.6.0

### ISSUE THREAD

**Issue by doko42** [bneijt/ccbuild#31]
seen at https://bugs.debian.org/812974 (not pasting the complete build log)

**Comment by tmancill** [comment]
Hi Bram.  The Debian packaging of ccbuild 2.0.7 was successful against flex 2.5.39.  I haven't looked into it very deeply, but perhaps this [flex changelog entry](https://anonscm.debian.org/cgit/users/srivasta/debian/flex.git/tree/ChangeLog#n73) is related?

**Comment by tmancill** [comment]
Thank you!  I will get a new Debian upload prepared soon.
